### ISSUE TITLE
Init Containers in istio-cni enabled namespaces have no network

### ISSUE THREAD

**Issue by geNAZt** [istio/cni#77]
Currently we are seeing a bug that our jenkins init container can't download its plugin (it does so in a init container to prepare the jenkins config). When we use istio 1.0.5 without CNI it works fine, traffic is only blocked once the init container from istio is done. With the CNI however all traffic is blocked until envoy is ready. 

What i would expect:
All traffic inside a init container is allowed.

Currently:
All traffic before the istio envoy sidecar is loaded is blocked.

**Comment by luksa** [comment]
@geNAZt I'd like to know more about your specific use-case. Why do you want all traffic to be allowed while the init container runs? Doesn't it make more sense for istio traffic management to be in place for the whole lifetime of the pod - including for the init containers?

**Comment by geNAZt** [comment]
We use the Jenkins Helm chart which has a init container which downloads plugins defined before Jenkins runs. It would be fine if traffic would be managed for init containers since i only route internal IPs through Istio so that wouldn't affect me.

**Comment by john-a-joyce** [comment]
I don't see how this is a CNI issue.   It seems like your current use case is exploiting a bit a security hole in the case no CNI is used as you aren't constrained to the the network limitations that were intended at config time due to the start-up transition period.   I think many would consider it an advantage that those constraints are in place for the entire pod life cycle.   Additionally Istio does not mandate you use CNI it is an option so unless you can convince me this is a use case the CNI must address I will close this issue in a few days.

**Comment by edude03** [comment]
@john-a-joyce I think I'm misunderstanding your position here, are you saying that init containers should not have network access and this is expected behavior? Our use case is that we use init containers for things like downloading files for batch jobs and running migrations for services.

**Comment by mikearnaldi** [comment]
another common use case for network in init containers is secret management using vault.

**Comment by edude03** [comment]
Ah I forgot about that @mikearnaldi, we do that as well 😆

**Comment by john-a-joyce** [comment]
I am not judging the merit of use cases or saying that init containers should have no network access.   You have a use case that requires it.   What I am saying is the nature of the CNI feature is to setup the network end state for the pod before any containers come up including init containers.   During discussions about using the CNI vs. init containers there were many use cases where that was a desirable behavior.  To put it differently the initial CNI implementation was designed specifically in a way that it would block your use case.   So this isn't a bug but instead you are asking the CNI to work in a different way.   It would be fine by me if someone wanted to present a proposal (or PR) on how to support this use case.   At least this should be changed to a feature request more than an issue.

**Comment by john-a-joyce** [comment]
We are being asked to move all CNI issues back to Istio so I am going to close this here.   Feel free to reopen it in the Istio repo as a feature request and we can discuss proposals on how to add this capability.

**Comment by howardjohn** [comment]
@john-a-joyce I think its valid to say that CNI is incompatible with init containers, but can we ever make CNI the default option if it breaks init containers?

**Comment by john-a-joyce** [comment]
@howardjohn - I don't think it is fair to say that the Istio CNi is incompatible with init containers.  It is only incompatible with init containers that want the pod network setup differently during the init container phase than the final networking for the app.   There are enough configuration options to allow the init containers to be directly connect to the network for all K8s deployment phases.  IMO many of the current requests exploit a bit of a hole where the pod networking is less restrictive while init containers are active than the final networking state.   Previously,   there were very strong opinions that that hole should be closed.   If someone is able to propose a solution that both closes the security hole that allowed complete network access during the init container phase while still allowing init container access as requested in this issue we are more than willing to support the proposal.

**Comment by dimpavloff** [comment]
>  It is only incompatible with init containers that want the pod network setup differently during the init container phase than the final networking for the app. 

Perhaps I'm misunderstanding the original issue but if the CNI plugin is configured to redirect traffic only for certain CIDRs (e.g. the K8s Pod/Service CIDR for the given cluster), then the above use case for Jenkins and Vault (assuming it's outside of K8s as is my case) should work -- i.e. there is no deviation from the final networking setup for the app. This can be done by annotating the Pods with `traffic.sidecar.istio.io/includeOutboundIPRanges` . 
However, asking the owners of the Pods to do this feels wrong and it would be much better to handle it on a cluster level. This is what already happens if you install Istio with `istio-init`  -- the cluster owners can set   `global.proxy.includeIPRanges` which `istio-init` factors in when creating the iptables rules. At the moment, it seems that this option is ignored by the CNI installation and there is no other way to provide `traffic.sidecar.istio.io/includeOutboundIPRanges` other than writing your own Admission hook or manually modifying the K8s Deployment (and making it environment-aware in the process..)

**Comment by john-a-joyce** [comment]
That is indeed an issue an a PR is in flight to fix that.  See PR 14171.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dimpavloff** [comment]
> That is indeed an issue an a PR is in flight to fix that. See PR 14171. 

Brilliant, thank you for already looking into it! :tada:
